### ISSUE TITLE
Make "Load ROM" dialog filter by .nes files

### ISSUE THREAD

**Issue by AndrewBelt** [Kautenja/RackNES#3]
Adding a file extension filter makes it easier for users to load the correct ROM file. osdialog supports extension filters with the following code.

```
osdialog_filters *filters = osdialog_filters_parse("NES ROM:nes,NES");
char *path = osdialog_file(OSDIALOG_OPEN, dir.c_str(), NULL, filters);
osdialog_filters_free(filters);
```

**Comment by Kautenja** [comment]
Sweet! I didn't know about this functionality.
